version: '3.7'

services:
  squash-tm-md:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: squash-root
      MARIADB_USER: squash_user
      MARIADB_PASSWORD: squash_password
      MARIADB_DATABASE: squash_db
    ports:
      - "3308:3306"  # Port changé ici
    volumes:
      - "/var/lib/mysql-db:/var/lib/mysql"

  squash-tm:
    image: squashtest/squash-tm
    depends_on:
      - squash-tm-md
    environment:
      SQTM_DB_TYPE: mariadb
      SQTM_DB_USERNAME: squash_user
      SQTM_DB_PASSWORD: squash_password
      SQTM_DB_NAME: squash_db
      SQTM_DB_HOST: squash-tm-md
      SQTM_DB_PORT: 3306  # Reste 3306 car on se connecte au port interne du conteneur
    ports:
      - "8090:8080"
    volumes:
      - squash-tm-logs:/opt/squash-tm/logs
      - squash-tm-plugins:/opt/squash-tm/plugins

volumes:
  squash-tm-logs:
  squash-tm-plugins: